// lib/courses-data.js

export const COURSES = [
  {
    slug: 'foundation',
    name: 'SAMADHI',
    tagline: 'A UPSC Foundation Course',
    badge: 'Most Popular',
    badgeColor: '#fcc419',
    category: 'Foundation',
    shortDesc:
      'Build an unshakeable GS foundation. Covers all four GS papers, CSAT, Essay, and Current Affairs in an integrated batch.',
    fullDesc: `SAMADHI is our flagship UPSC foundation course designed for beginners and serious aspirants starting fresh. The name reflects the deep focus and concentration required to conquer India's toughest exam. We cover the complete UPSC CSE syllabus — GS 1, 2, 3, 4, Essay, CSAT — in a structured, time-bound manner with daily accountability.`,
    duration: '12 Months',
    mode: 'Online + Offline',
    batchSize: 'Max 25 students',
    startDate: 'January 9, 2026',
    highlights: [
      'Complete GS 1, 2, 3, 4 coverage',
      'Weekly Prelims + Mains tests',
      'Essay writing workshops',
      'Current affairs integration (daily)',
      'CSAT batch included',
      'One-to-one doubt sessions',
      'Printed study material',
      'Monthly parent progress reports',
    ],
    syllabus: [
      { title: 'GS Paper 1', topics: 'History, Geography, Art & Culture, Indian Society' },
      { title: 'GS Paper 2', topics: 'Polity, Governance, IR, Social Justice' },
      { title: 'GS Paper 3', topics: 'Economy, Agriculture, Environment, S&T, Security' },
      { title: 'GS Paper 4', topics: 'Ethics, Integrity, Aptitude, Case Studies' },
      { title: 'Essay', topics: 'Structure, argument building, weekly practice' },
      { title: 'CSAT', topics: 'Reading comprehension, reasoning, math basics' },
    ],
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80',
    price: '₹45,000',
    rating: 4.9,
    students: '200+',
    color: '#fcc419',
  },
  {
    slug: 'prelims',
    name: 'ASPIRE',
    tagline: 'Achieve Success in Prelims via Intellectual Resources Enrichment',
    badge: 'High Demand',
    badgeColor: '#748ffc',
    category: 'Prelims',
    shortDesc:
      'Laser-focused Prelims preparation with 5000+ MCQs, PYQ analysis, daily quizzes, and full-length Sunday mock tests.',
    fullDesc: `ASPIRE is built exclusively for Prelims clearing. We follow a data-driven approach — analysing 10 years of PYQs to identify high-yield topics, then drilling those concepts through daily quizzes and weekly full-lengths. CSAT is fully integrated. Our 95%+ Prelims clearing rate in the last 3 batches speaks for itself.`,
    duration: '6 Months',
    mode: 'Online + Offline',
    batchSize: 'Max 30 students',
    startDate: 'February 1, 2026',
    highlights: [
      '5000+ curated MCQs with explanations',
      'PYQ analysis (2014–2025)',
      'Daily 20-question quiz',
      'Full-length Sunday mock test',
      'CSAT module included',
      'Elimination technique workshops',
      'Rapid revision capsules',
      'Rank predictor after each mock',
    ],
    syllabus: [
      { title: 'History & Culture', topics: 'Ancient, Medieval, Modern, Art & Culture' },
      { title: 'Geography', topics: 'Physical, Indian, World, Environment' },
      { title: 'Polity', topics: 'Constitution, Parliament, Judiciary, Local Bodies' },
      { title: 'Economy', topics: 'Basic concepts, Budget, Schemes, Banking' },
      { title: 'Science & Technology', topics: 'Space, Defence, Biotech, ICT' },
      { title: 'CSAT', topics: 'Reading, Reasoning, Data Interpretation, Math' },
    ],
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80',
    price: '₹25,000',
    rating: 4.8,
    students: '180+',
    color: '#748ffc',
  },
  {
    slug: 'mains-answer-writing',
    name: 'RE-RAW',
    tagline: 'Resources Enrichment With Rigorous Answer Writing',
    badge: 'Top Ranked',
    badgeColor: '#51cf66',
    category: 'Mains',
    shortDesc:
      'The only program that evaluates every answer you write — with detailed written feedback from faculty within 48 hours.',
    fullDesc: `RE-RAW is Success Education's most intensive Mains answer writing program. Most aspirants know the content but struggle to score — because writing is a skill that requires repeated practice and structured feedback. RE-RAW gives you daily writing prompts, weekly evaluated assignments, and monthly synopsis reviews, all mapped to the UPSC Mains pattern.`,
    duration: '4 Months',
    mode: 'Online + Offline',
    batchSize: 'Max 20 students',
    startDate: 'March 1, 2026',
    highlights: [
      'Daily answer writing prompt',
      '48-hour faculty feedback guarantee',
      'Monthly Secure Synopsis reviews',
      'Essay evaluation (2 per week)',
      'GS 4 case study workshops',
      'Model answers from top rankers',
      'Introduction to answer enrichment',
      'Previous Mains papers fully solved',
    ],
    syllabus: [
      { title: 'Answer Structure', topics: 'Intro, body, conclusion, keyword usage' },
      { title: 'GS 1 Writing', topics: 'History, geography, society answers' },
      { title: 'GS 2 Writing', topics: 'Polity, IR, governance answers' },
      { title: 'GS 3 Writing', topics: 'Economy, environment, security answers' },
      { title: 'GS 4 Writing', topics: 'Ethics case studies, philosophical questions' },
      { title: 'Essay', topics: 'Long-form essay planning, drafting, editing' },
    ],
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80',
    price: '₹18,000',
    rating: 4.9,
    students: '150+',
    color: '#51cf66',
  },
  {
    slug: 'mentorship',
    name: 'SAHAYAK',
    tagline: 'A Personal Mentorship Support Program',
    badge: 'Premium',
    badgeColor: '#ff6b6b',
    category: 'Mentorship',
    shortDesc:
      'One-to-one personalised mentorship with an IAS/IPS mentor who reviews your strategy, study plan, and progress every week.',
    fullDesc: `SAHAYAK pairs you with a dedicated UPSC mentor — a cleared IAS/IPS officer or a top-ranked final stage aspirant. Your mentor reviews your weekly plan, answers your doubts, evaluates your answers, and keeps you on track psychologically. This is for aspirants who want a human guiding hand through the 2-year UPSC journey.`,
    duration: '12 Months',
    mode: 'Online (1-on-1 sessions)',
    batchSize: 'Individual only',
    startDate: 'Rolling admissions',
    highlights: [
      'Dedicated personal mentor assigned',
      'Weekly 1-hour video call',
      'Personalised study plan (monthly)',
      'Unlimited WhatsApp doubt support',
      'Answer evaluation (5 per week)',
      'Mock interview sessions (3 included)',
      'Psychological coaching + motivation',
      'Strategy pivot if needed mid-year',
    ],
    syllabus: [
      { title: 'Month 1-2', topics: 'Goal setting, baseline assessment, study plan creation' },
      { title: 'Month 3-5', topics: 'Foundation building, weekly check-ins' },
      { title: 'Month 6-8', topics: 'Mains answer writing, current affairs integration' },
      { title: 'Month 9-10', topics: 'Revision strategy, mock tests, analysis' },
      { title: 'Month 11', topics: 'Mock interviews, personality refinement' },
      { title: 'Month 12', topics: 'Final preparation, mental preparation' },
    ],
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
    price: '₹35,000',
    rating: 5.0,
    students: '80+',
    color: '#ff6b6b',
  },
  {
    slug: 'test-series',
    name: 'ENDURANCE',
    tagline: 'Full Length Prelims Mock Test Every Sunday',
    badge: 'New Batch',
    badgeColor: '#fcc419',
    category: 'Test Series',
    shortDesc:
      'Weekly full-length Prelims mock tests, all-India ranking, deep analysis, and rank tracking from January to May.',
    fullDesc: `ENDURANCE is our comprehensive Prelims test series running from January to June every year. Every Sunday you write a 200-question full-length test under exam conditions. Post-test, you get an all-India rank, topic-wise accuracy report, and a 2-hour video analysis of the test with faculty. We simulate the exact UPSC exam experience.`,
    duration: '5 Months (Jan–June)',
    mode: 'Online + Offline Centre',
    batchSize: 'Open batch',
    startDate: 'January 5, 2026',
    highlights: [
      '20 full-length Prelims mock tests',
      '4 CSAT-only mock tests',
      'All-India ranking after each test',
      'Topic-wise accuracy analytics',
      '2-hour post-test video analysis',
      'Rank tracker dashboard',
      'PYQ-mapped question bank',
      'Last-minute revision capsules',
    ],
    syllabus: [
      { title: 'Phase 1 (Jan-Feb)', topics: 'Sectional tests — History, Polity, Geography' },
      { title: 'Phase 2 (Mar)', topics: 'Sectional tests — Economy, Environment, S&T' },
      { title: 'Phase 3 (Apr-May)', topics: 'Full-length integrated tests' },
      { title: 'Phase 4 (May-Jun)', topics: 'Revision tests + CSAT intensives' },
    ],
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80',
    price: '₹8,000',
    rating: 4.7,
    students: '500+',
    color: '#fcc419',
  },
  {
    slug: 'interview',
    name: 'ANUBHAVI',
    tagline: 'Navigate The Path to Professional Excellence',
    badge: 'Elite',
    badgeColor: '#748ffc',
    category: 'Interview',
    shortDesc:
      'Comprehensive IAS interview preparation with mock boards, DAF analysis, current affairs grilling, and personality refinement.',
    fullDesc: `ANUBHAVI is our Interview / Personality Test preparation program designed for Mains-cleared aspirants. The UPSC interview is 275 marks and can make or break your rank. Our mock board panels include retired IAS, IPS, and UPSC board members. We focus on DAF-based questioning, current affairs depth, and authentic personality refinement — not scripted answers.`,
    duration: '45 Days',
    mode: 'Offline preferred / Online',
    batchSize: 'Max 10 students',
    startDate: 'Rolling (post Mains result)',
    highlights: [
      '5 mock interview boards included',
      'DAF (Detailed Application Form) deep dive',
      'Current affairs grilling sessions',
      'Retired IAS/IPS on mock panels',
      'Video recording + playback analysis',
      'Body language coaching',
      'Optional subject corner questions',
      'Certificate of completion',
    ],
    syllabus: [
      { title: 'Week 1', topics: 'DAF analysis, personal narrative building' },
      { title: 'Week 2', topics: 'Current affairs intensive, opinion formation' },
      { title: 'Week 3', topics: 'Mock boards 1, 2, 3 — full recording + review' },
      { title: 'Week 4-5', topics: 'Mock boards 4, 5 — refinement, final prep' },
      { title: 'Week 6', topics: 'Confidence building, last-minute preparation' },
    ],
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&q=80',
    price: '₹12,000',
    rating: 4.9,
    students: '120+',
    color: '#748ffc',
  },
  {
    slug: 'law-answer-writing',
    name: 'LAW',
    tagline: 'Learn The Art of Answer Writing',
    badge: 'Specialist',
    badgeColor: '#51cf66',
    category: 'Mains',
    shortDesc:
      'Dedicated law optional + general answer writing program focusing on precision, citation, and structured argumentation.',
    fullDesc: `LAW is a specialist program for aspirants who have chosen Law as their optional subject and those who want to master GS Mains answer writing with legal precision. We cover the complete Law optional syllabus alongside answer writing techniques. Faculty consists of practising advocates and ex-civil servants with Law backgrounds.`,
    duration: '8 Months',
    mode: 'Online + Offline',
    batchSize: 'Max 15 students',
    startDate: 'February 15, 2026',
    highlights: [
      'Complete Law Optional syllabus (Paper 1 & 2)',
      'Constitutional law deep dive',
      'Case law application in answers',
      'Landmark judgement analysis',
      'GS 2 governance & polity overlap',
      'Weekly evaluated answers',
      'Past years Law optional papers',
      'Advocate faculty panel',
    ],
    syllabus: [
      { title: 'Paper 1 — Jurisprudence', topics: 'Nature of law, schools, legal rights, liability' },
      { title: 'Paper 1 — Constitutional Law', topics: 'Constitution, fundamental rights, DPSP, amendments' },
      { title: 'Paper 2 — International Law', topics: 'Treaties, UN, state responsibility, human rights' },
      { title: 'Paper 2 — Law of Crimes', topics: 'IPC, Evidence Act, criminal procedure' },
      { title: 'Answer Writing', topics: 'Citation, argumentation, structured answers' },
    ],
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80',
    price: '₹22,000',
    rating: 4.8,
    students: '90+',
    color: '#51cf66',
  },
  {
    slug: 'ncert-foundation',
    name: 'UDAY',
    tagline: 'NCERT Orientation and Concept Building',
    badge: 'For Beginners',
    badgeColor: '#ff6b6b',
    category: 'Foundation',
    shortDesc:
      'Start your UPSC journey the right way — mastering all relevant NCERTs from Class 6 to 12 before diving into advanced resources.',
    fullDesc: `UDAY is the starting point for serious UPSC aspirants who want to get their basics absolutely right. Most failures happen because aspirants skip NCERT foundations. UDAY ensures you cover all relevant Class 6–12 NCERTs (History, Geography, Science, Economy, Polity) with concept maps, notes, and weekly tests before moving to standard reference books.`,
    duration: '3 Months',
    mode: 'Online + Offline',
    batchSize: 'Max 30 students',
    startDate: 'January 9, 2026',
    highlights: [
      'All relevant NCERTs (Class 6–12)',
      'Concept maps for every chapter',
      'Weekly NCERT-based MCQ test',
      'Short notes provided',
      'Doubt clearing after every NCERT',
      'Transition guidance to standard books',
      'Maps and diagrams included',
      'Perfect complement to SAMADHI',
    ],
    syllabus: [
      { title: 'Month 1', topics: 'History NCERTs (Old + New) + Geography NCERTs' },
      { title: 'Month 2', topics: 'Science NCERTs + Economy NCERTs (Class 11-12)' },
      { title: 'Month 3', topics: 'Polity NCERT + Social Science + Revision' },
    ],
    image: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=800&q=80',
    price: '₹6,000',
    rating: 4.8,
    students: '300+',
    color: '#ff6b6b',
  },
];

export function getCourseBySlug(slug) {
  return COURSES.find((c) => c.slug === slug) || null;
}